source 'https://rubygems.org'

gem 'ruby-opencv', :git => 'git://github.com/ruby-opencv/ruby-opencv.git'
gem 'nokogiri'
gem 'rmagick'
gem 'sidekiq'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'json'
gem 'pusher'
gem 'foreman'
gem 'puma'